#### 1. Import the numpy package under the name `np` (★☆☆)


In [136]:
import numpy as np
import warnings
warnings.filterwarnings('ignore')

#### 2. Print the numpy version and the configuration (★☆☆)

In [5]:
np.version.version

'1.22.4'

#### 3. Create a null vector of size 10 (★☆☆)

In [8]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [9]:
x = np.zeros(10)
  
print("Size of the array: ",
      x.size)
  
print("Memory size of one array element in bytes: ",x.itemsize)
  
# memory size of numpy array in bytes
print("Memory size of numpy array in bytes:",
      x.size * x.itemsize)

Size of the array:  10
Memory size of one array element in bytes:  8
Memory size of numpy array in bytes: 80


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [14]:
print(np.info())

 info(object=None, maxwidth=76,
      output=<ipykernel.iostream.OutStream object at 0x0000018CA75D5C40>,
      toplevel='numpy')

Get help information for a function, class, or module.

Parameters
----------
object : object or str, optional
    Input object or name to get information about. If `object` is a
    numpy object, its docstring is given. If it is a string, available
    modules are searched for matching objects.  If None, information
    about `info` itself is returned.
maxwidth : int, optional
    Printing width.
output : file like object, optional
    File like object that the output is written to, default is
    ``stdout``.  The object has to be opened in 'w' or 'a' mode.
toplevel : str, optional
    Start search at this level.

See Also
--------
source, lookfor

Notes
-----
When used interactively with an object, ``np.info(obj)`` is equivalent
to ``help(obj)`` on the Python prompt or ``obj?`` on the IPython
prompt.

Examples
--------
>>> np.info(np.polyval) # doctest: +

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [18]:
x=np.zeros(10) 
x[4]=1  
x

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [20]:
np.arange(10,49)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [21]:
x=np.arange(10,49)
x[::-1]

array([48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [23]:
np.arange(0, 9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find the indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [47]:
nums = np.array([1,2,0,0,4,0])
print("Original array:")
print(nums)
print("Indices of elements equal to zero of the said array:")
result = np.where(nums!= 0)[0]
print(result)

Original array:
[1 2 0 0 4 0]
Indices of elements equal to zero of the said array:
[0 1 4]
(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [34]:
import numpy as np
array_2D=np.identity(3)
print(array_2D)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [35]:
np.random.random((3,3,3))

array([[[0.40468298, 0.49684892, 0.39455574],
        [0.17215513, 0.10755064, 0.58805626],
        [0.01357897, 0.57909115, 0.14149016]],

       [[0.48491381, 0.27323959, 0.32761169],
        [0.77411239, 0.50259687, 0.90807943],
        [0.10551795, 0.57482498, 0.493583  ]],

       [[0.03339581, 0.92758232, 0.88195693],
        [0.08498408, 0.35092474, 0.64578182],
        [0.92453273, 0.05753172, 0.64844254]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [45]:
x = np.random.random((5,5))
print(x) 
print("------------------max min--------------")
print("{} Min {} Max".format(x.min(), x.max()))

[[0.46802046 0.11387585 0.69330325 0.98127326 0.6472264 ]
 [0.94804068 0.87984086 0.1865454  0.60903293 0.83282136]
 [0.88206873 0.42523638 0.237483   0.17457066 0.28961238]
 [0.13458504 0.57685065 0.62700553 0.7868227  0.09569259]
 [0.80756335 0.72586117 0.15446186 0.74989449 0.516527  ]]
------------------max min--------------
0.09569259352099524 Min 0.981273261744318 Max


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [52]:
Z = np.random.random(30)
print(Z)
print("---------------mean------------------")
m = Z.mean()
print (m)

[0.7432533  0.68887163 0.79648616 0.9805515  0.28925011 0.01245834
 0.21081009 0.22720257 0.35305622 0.62127653 0.64944587 0.39231941
 0.03391465 0.67912406 0.57040769 0.05982281 0.40417738 0.03456752
 0.79888219 0.57931769 0.94550286 0.93851191 0.52606721 0.17166599
 0.36211924 0.68514485 0.01278034 0.65909858 0.90629814 0.81014103]
---------------mean------------------
0.5047508631448561


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [55]:
Z = np.ones((10,10))
Z[1:-1,1:-1]=0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [59]:
x = np.ones((3,3))
print(x)
print("0 on the border and 1 inside in the array")
x= np.pad(x, pad_width=1, mode='constant')

print(x)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
0 on the border and 1 inside in the array
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
     ```python
    0 * np.nan
    np.nan == np.nan
    np.inf > np.nan
    np.nan - np.nan
    np.nan in set([np.nan])
    0.3 == 3 * 0.1

In [74]:
a = 0 * np.nan
b = np.nan == np.nan
c = np.inf > np.nan
d = np.nan - np.nan
e = np.nan in set([np.nan])
f = 0.3 == 3 * 0.1
print(a,b,c,d,e,f, sep='\n')

nan
False
False
nan
True
False


### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [79]:
np.diag(1+np.arange(4))


array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [89]:
mat = np.ones((8,8))
mat[1::2, ::2]= 0
mat[::2, 1::2] = 0
mat

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [91]:
np.unravel_index(100, (6,7,8))

(1, 5, 4)

### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [92]:
array= np.array([[0,1], [1,0]])
np.tile(array,(4,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

### 22. Normalize a 5x5 random matrix (★☆☆)

In [93]:
Z = np.random.random((5,5))
Zmax, Zmin = Z.max(), Z.min()
Z= (Z-Zmin)/(Zmax-Zmin)
print (Z)

[[0.05402511 0.02164265 0.56092792 0.49340561 0.99814499]
 [0.71301298 0.01647087 0.12303921 0.28316823 0.22024511]
 [0.48112302 0.76118402 0.97339203 0.97486946 0.31424109]
 [0.21347434 1.         0.88077323 0.78446772 0.9878335 ]
 [0.76202698 0.25277338 0.         0.82909243 0.7095446 ]]


### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [96]:
RGBA = np.dtype([('red',np.uint8),('green',np.uint8),('blue',np.uint8),('alpha',np.uint8)])
color = np.array((1,2,4,3),dtype = RGBA)
print(color['green'])
type(color)

2


numpy.ndarray

### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [97]:
np.dot(np.ones((5,3)), np.ones((3,2)))

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [109]:
Z = np.arange(11)
Z[(3 < Z) & (Z <= 8)] *= -1
Z

array([ 0,  1,  2,  3, -4, -5, -6, -7, -8,  9, 10])

### 26. What is the output of the following script? (★☆☆)
#### Author: Jake VanderPlas
    print(sum(range(5),-1))
    from numpy import *
    print(sum(range(5),-1))

In [110]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10


### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
    Z**Z
    2 << Z >> 2
    Z <- Z
    1j*Z
    Z/1/1
    Z<Z>Z

In [119]:
Z = arange(10)

print(Z**Z)
print(2 << Z >> 2)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)
# print(Z<Z>Z) error

[        1         1         4        27       256      3125     46656
    823543  16777216 387420489]
[  0   1   2   4   8  16  32  64 128 256]
[False False False False False False False False False False]
[0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j 0.+5.j 0.+6.j 0.+7.j 0.+8.j 0.+9.j]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


### 28. What are the result of the following expressions? (★☆☆)
    np.array(0) / np.array(0)
    np.array(0) // np.array(0)
    np.array([np.nan]).astype(int).astype(float)

In [137]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


### 29. How to round away from zero a float array ? (★☆☆)

In [122]:
arr = np.random.random((5,5))
print(arr)
arr = np.round(arr,2)
print(arr) 

[[0.08391934 0.97970489 0.37109897 0.4090593  0.42092772]
 [0.10854181 0.78200312 0.86150251 0.8426544  0.07291334]
 [0.27103339 0.09493598 0.63538808 0.87145974 0.34497757]
 [0.52058734 0.69412095 0.87565398 0.22969771 0.10611434]
 [0.41603311 0.80392921 0.14397174 0.63539628 0.83717299]]
[[0.08 0.98 0.37 0.41 0.42]
 [0.11 0.78 0.86 0.84 0.07]
 [0.27 0.09 0.64 0.87 0.34]
 [0.52 0.69 0.88 0.23 0.11]
 [0.42 0.8  0.14 0.64 0.84]]


### 30. How to find common values between two arrays? (★☆☆)

In [130]:
arr_1 = np.arange(9).reshape(3,3)
arr_2 = np.array([[0,1,2],[3,56,5],[1,1,1]])

#indices = [i for i,x,y in enumerate(arr_1,arr_2) if (x ==y) ]

indices = (arr_1 == arr_2)
print("1st Array")
print(arr_1)
print("2nd Array")
print(arr_2)
print("comman value of 2 arry")
arr_1[indices]

1st Array
[[0 1 2]
 [3 4 5]
 [6 7 8]]
2nd Array
[[ 0  1  2]
 [ 3 56  5]
 [ 1  1  1]]
comman value of 2 arry


array([0, 1, 2, 3, 5])

### 32. Is the following expressions true? (★☆☆)
    np.sqrt(-1) == np.emath.sqrt(-1)

In [138]:
print(np.sqrt(-1))
print(np.emath.sqrt(-1))
np.sqrt(-1) == np.emath.sqrt(-1)

nan
1j


False

### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [143]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("yesterday",yesterday,"today",today,"tomorrow",tomorrow, sep='\n')

yesterday
2022-09-01
today
2022-09-02
tomorrow
2022-09-03


### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [144]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [146]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
print(np.add(A,B,out=B))
print(np.divide(A,2,out=A))
print(np.negative(A,out=A))
print(np.dot(A,B))

[3. 3. 3.]
[0.5 0.5 0.5]
[-0.5 -0.5 -0.5]
-4.5


### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [150]:
Z = np.random.uniform(0,10,10)
print(Z)
print (Z - Z%1)
print (np.floor(Z))
print (np.ceil(Z)-1)
print (Z.astype(int))

[2.94137101 3.76216963 3.60637392 8.86579361 0.45192671 1.52482508
 0.07257802 8.30941011 9.6229966  8.76757193]
[2. 3. 3. 8. 0. 1. 0. 8. 9. 8.]
[2. 3. 3. 8. 0. 1. 0. 8. 9. 8.]
[2. 3. 3. 8. 0. 1. 0. 8. 9. 8.]
[2 3 3 8 0 1 0 8 9 8]


### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [151]:
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [152]:
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [154]:
Z = np.linspace(0,1,11,endpoint=False)[1:]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


### 40. Create a random vector of size 10 and sort it (★★☆)

In [156]:
Z = np.random.random(10)
Z.sort()
Z

array([0.11425969, 0.13954612, 0.19040463, 0.28192466, 0.40725586,
       0.41631144, 0.44677705, 0.46069024, 0.61275042, 0.76778199])

### 41. How to sum a small array faster than np.sum? (★★☆)

In [157]:
arr = np.arange(10)
np.add.reduce(arr)

45

### 42. Consider two random array A and B, check if they are equal (★★☆)

In [159]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

equal = np.allclose(A,B)
print(equal)

equal = np.array_equal(A,B)
print(equal)

False
False


### 43. Make an array immutable (read-only) (★★☆)

In [160]:
Z = np.zeros(10)

Z.flags.writeable = False

Z[0] = 1

ValueError: assignment destination is read-only

### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [161]:
Z = np.random.random((10,2))

X,Y = Z[:,0], Z[:,1]

R = np.sqrt(X**2+Y**2)

T = np.arctan2(Y,X)

print(R)

print(T)

[0.74811923 1.21234984 0.93422135 0.84667001 0.85080626 0.37304903
 0.46246471 1.19214059 0.46861561 0.938632  ]
[0.90808933 0.60737554 0.48906001 0.61861391 0.51591568 0.42709358
 0.77008156 0.73654543 0.94227053 0.33120066]


### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [167]:
z = np.arange(10)
max(z)
print(z.argmax())
z[9] = 0
print(z)

9
[0 1 2 3 4 5 6 7 8 0]


### 46. Create a structured array with x and y coordinates covering the [0,1]x[0,1] area (★★☆)

In [163]:
arr = np.zeros((5,5), [('x',float),('y',float)])
arr['x'], arr['y'] = np.meshgrid(np.linspace(0,1,5),np.linspace(0,1,5))
print(arr)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [168]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.163637117973


### 48. Print the minimum and maximum representable value for each numpy scalar type(★★☆)

In [170]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)

for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


### 49. How to print all the values of an array? (★★☆)

In [173]:
# np.set_printoptions(threshold=np.nan)
# Z = np.zeros((25,25))
# print(Z)

### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [179]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])

78


### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [182]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1),('y', float, 1)]),
                    ('color',[ ('r', float, 1),('g', float, 1),('b', float, 1)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [183]:
Z = np.random.random((10,2))

X,Y = np.atleast_2d(Z[:,0], Z[:,1])

D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)

print(D)

[[0.         0.36598937 0.68324996 0.21967114 0.4084966  0.11119389
  0.37392465 0.77238899 0.35716661 0.33981995]
 [0.36598937 0.         0.54076449 0.49141447 0.18992549 0.45267272
  0.04733289 0.40795675 0.09313051 0.18637821]
 [0.68324996 0.54076449 0.         0.89610813 0.35311743 0.68089791
  0.49343178 0.68538182 0.63332079 0.72099713]
 [0.21967114 0.49141447 0.89610813 0.         0.59266861 0.28136474
  0.51709476 0.86519348 0.4412278  0.37570663]
 [0.4084966  0.18992549 0.35311743 0.59266861 0.         0.45589461
  0.14310469 0.47499255 0.28117879 0.36790712]
 [0.11119389 0.45267272 0.68089791 0.28136474 0.45589461 0.
  0.45201032 0.86041957 0.45744735 0.44865378]
 [0.37392465 0.04733289 0.49343178 0.51709476 0.14310469 0.45201032
  0.         0.41173032 0.14024624 0.23206759]
 [0.77238899 0.40795675 0.68538182 0.86519348 0.47499255 0.86041957
  0.41173032 0.         0.42702927 0.49218878]
 [0.35716661 0.09313051 0.63332079 0.4412278  0.28117879 0.45744735
  0.14024624 0.42702

### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [185]:
arr = np.arange(10, dtype=np.int32)
print(arr)

arr = arr.astype(np.float32, copy=False)

print(arr)

[0 1 2 3 4 5 6 7 8 9]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


### 54. How to read the following file? (★★☆)
    1, 2, 3, 4, 5
    6, , , 7, 8
    , , 9,10,11

In [187]:
from io import StringIO

# Fake file 
s = StringIO("""1, 2, 3, 4, 5\n
                6,  ,  , 7, 8\n
                 ,  , 9,10,11\n""")
Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [191]:
arr = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(arr):
    print(index, value)
print('-'*60)
for index in np.ndindex(arr.shape):
    print(index, arr[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
------------------------------------------------------------
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [194]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0

G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

### 57. How to randomly place p elements in a 2D array? (★★☆)

In [195]:
n = 10
p = 3
arr = np.zeros((n,n))
np.put(arr, np.random.choice(range(n*n), p, replace=False),1)

print(arr)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


### 58. Subtract the mean of each row of a matrix (★★☆)

In [196]:
X = np.random.rand(5, 10)

Y = X - X.mean(axis=1, keepdims=True)

print(Y)

[[ 0.28221238 -0.52251352 -0.17008713 -0.22939749 -0.05852276 -0.36299054
   0.34899966  0.35852549 -0.06935906  0.42313297]
 [ 0.09738559 -0.11810419 -0.0504089  -0.24065894 -0.03609296  0.27001523
   0.01251531  0.05430679  0.24480705 -0.23376498]
 [ 0.01159337  0.17729411 -0.08976366  0.33526657 -0.1923002  -0.08728394
  -0.18331934  0.13032372 -0.18758169  0.08577106]
 [ 0.44577364 -0.01132225 -0.00076536 -0.34855702 -0.03115155  0.39001977
  -0.10819643 -0.00292494 -0.35959969  0.02672383]
 [-0.35550854 -0.26378894 -0.11944711  0.19615561  0.21189155  0.28262388
   0.56989553  0.10677137 -0.23606001 -0.39253335]]


### 59. How to sort an array by the nth column? (★★☆)

In [199]:
arr = np.random.randint(10,20,(3,3))
print(arr)

print(arr[arr[:,1].argsort()])

[[14 12 10]
 [12 18 15]
 [14 10 15]]
[[14 10 15]
 [14 12 10]
 [12 18 15]]


### 60. How to tell if a given 2D array has null columns? (★★☆)

In [201]:
arr = np.random.randint(0,3,(3,10))
print(arr)
print((~arr.any(axis=0)).any())

[[1 0 1 0 2 1 1 0 0 2]
 [1 0 1 1 1 1 0 2 0 2]
 [2 1 2 0 2 2 1 0 1 1]]
False


### 61. Find the nearest value from a given value in an array (★★☆)

In [205]:
arr = np.random.uniform(0,1,10)

arr1 = 0.5

m = arr.flat[np.abs(arr - arr1).argmin()]

print(m)

0.5766331287824835


### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)



In [206]:
A = np.arange(3).reshape(3,1)

B = np.arange(3).reshape(1,3)

it = np.nditer([A,B,None])

for x,y,z in it: z[...] = x + y

print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


###  63. Create an array class that has a name attribute (★★☆)

In [209]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj

def __array_finalize__(self, obj):
    if obj is None: return
    self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")

print (Z.name)

range_10


### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [212]:
Z = np.ones(10)

I = np.random.randint(0,len(Z),20)

Z += np.bincount(I, minlength=len(Z))

print(Z)

np.add.at(Z, I, 1)

print(Z)

[2. 2. 5. 4. 4. 3. 3. 3. 2. 2.]
[3. 3. 9. 7. 7. 5. 5. 5. 3. 3.]


### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list(I)? (★★★)

In [213]:
X = [1,2,3,4,5,6]

I = [1,3,9,3,4,1]

F = np.bincount(I,X)

print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [216]:
w,h = 16,16

I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)

F = I[...,0]*256*256 + I[...,1]*256 +I[...,2]

n = len(np.unique(F))

print(np.unique(I))

[0 1]


### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [218]:
A = np.random.randint(0,10,(3,4,3,4))

sum = A.sum(axis=(-2,-1))

print(sum)


[[45 42 44 51]
 [66 49 54 64]
 [54 46 41 58]]


### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset indices? (★★★)

In [220]:
D = np.random.uniform(0,1,100)

S = np.random.randint(0,10,100)

D_sums = np.bincount(S, weights=D)

D_counts = np.bincount(S)

D_means = D_sums / D_counts

print(D_means)

[0.70464394 0.4371483  0.35688546 0.50721573 0.4614733  0.43259724
 0.65646848 0.57098732 0.54519587 0.34697317]


### 69. How to get the diagonal of a dot product? (★★★)

In [224]:
A = np.random.uniform(0,1,(5,5))

B = np.random.uniform(0,1,(5,5))


np.diag(np.dot(A, B))

array([1.01817381, 1.3802931 , 0.95109183, 1.37952744, 0.90353391])

### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [226]:
Z = np.array([1,2,3,4,5])

nz = 3

Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))

Z0[::nz+1] = Z

print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


### 71. Consider an array of given dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [228]:
A = np.ones((5,5,3))

B = 2*np.ones((5,5))

print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


### 72. How to swap two rows of an array? (★★★)

In [232]:
A = np.arange(25,50).reshape(5,5)
print(A)

print("*"*60)

A[[2,3]] = A[[3,2]]

print(A)

[[25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]]
************************************************************
[[25 26 27 28 29]
 [30 31 32 33 34]
 [40 41 42 43 44]
 [35 36 37 38 39]
 [45 46 47 48 49]]


### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the triangles (★★★)

In [233]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)

F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)

G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )

G = np.unique(G)

print(G)

[( 2, 11) ( 2, 54) (10, 13) (10, 95) (11, 54) (13, 95) (22, 63) (22, 90)
 (25, 63) (25, 65) (31, 64) (31, 92) (39, 58) (39, 63) (41, 50) (41, 66)
 (49, 74) (49, 84) (50, 66) (58, 63) (62, 81) (62, 98) (63, 65) (63, 90)
 (64, 92) (69, 84) (69, 97) (74, 84) (81, 98) (84, 97)]


### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [234]:
C = np.bincount([1,1,2,3,4,4,6])

A = np.repeat(np.arange(len(C)), C)

print(A)

[1 1 2 3 4 4 6]


### 75. How to compute averages using a sliding window over an array? (★★★)

In [240]:
def moving_average(a, n=10) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n

Z = np.arange(100)

print(moving_average(Z, n=10))

[ 4.5  5.5  6.5  7.5  8.5  9.5 10.5 11.5 12.5 13.5 14.5 15.5 16.5 17.5
 18.5 19.5 20.5 21.5 22.5 23.5 24.5 25.5 26.5 27.5 28.5 29.5 30.5 31.5
 32.5 33.5 34.5 35.5 36.5 37.5 38.5 39.5 40.5 41.5 42.5 43.5 44.5 45.5
 46.5 47.5 48.5 49.5 50.5 51.5 52.5 53.5 54.5 55.5 56.5 57.5 58.5 59.5
 60.5 61.5 62.5 63.5 64.5 65.5 66.5 67.5 68.5 69.5 70.5 71.5 72.5 73.5
 74.5 75.5 76.5 77.5 78.5 79.5 80.5 81.5 82.5 83.5 84.5 85.5 86.5 87.5
 88.5 89.5 90.5 91.5 92.5 93.5 94.5]


### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [241]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)

Z = rolling(np.arange(10), 3)

print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [242]:
Z = np.random.randint(0,2,100)

np.logical_not(Z, out=Z)

Z = np.random.uniform(-1.0,1.0,100)

np.negative(Z, out=Z)

array([-0.71534157, -0.18057419, -0.72910693, -0.31372226, -0.7540441 ,
        0.19424878,  0.47599147,  0.64394731, -0.05143244, -0.80286994,
        0.29254534, -0.95780006, -0.24371829, -0.89260769, -0.16609357,
        0.19937286,  0.65959261, -0.02173638, -0.18449736, -0.8471405 ,
        0.35518744,  0.66454046, -0.65468625, -0.04517105,  0.11770587,
       -0.65877028,  0.12782621,  0.01137281,  0.30502233, -0.00387153,
        0.7406898 , -0.20511069, -0.16423608, -0.6454877 ,  0.24741559,
       -0.99744335, -0.18640226, -0.12886412, -0.3734599 ,  0.41516352,
       -0.99776001, -0.42390607,  0.53865136,  0.70636658, -0.95262987,
       -0.10618115,  0.26151427, -0.26685053,  0.80276328,  0.17056378,
        0.91281675,  0.67426252,  0.68661125,  0.94556888, -0.23375539,
        0.00296059, -0.75592265,  0.34300543, -0.51123534,  0.07421501,
        0.01317209,  0.32564043,  0.2787917 , -0.05970467, -0.6595585 ,
       -0.37194666, -0.34934556, -0.57278792,  0.53952041,  0.15

### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [243]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))

P1 = np.random.uniform(-10,10,(10,2))

p = np.random.uniform(-10,10,( 1,2))

print(distance(P0, P1, p))

[ 7.19370024 14.72354253  2.4190116   7.01855386  0.8565059   4.82070701
  6.90341209 13.88538018  2.22745523  4.52591627]


### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [244]:
P0 = np.random.uniform(-10, 10, (10,2))

P1 = np.random.uniform(-10,10,(10,2))

p = np.random.uniform(-10, 10, (10,2))

print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 0.0510955   8.46552277  3.6838583   2.49646948  9.27729683  6.32676304
  12.09791748  1.07340683  5.11950577  7.87899581]
 [ 0.49607797  1.16898357  5.71389612  4.16412784  1.07364133  3.18711462
   3.37679696  9.13256931  3.481025    0.51776385]
 [ 5.80693042  8.61861067  1.30706258  8.52535863  3.25814817  0.85462532
  13.19614562  0.47737034  6.32777611 10.08626383]
 [ 8.44086462  4.82371324 11.90280044  5.9728485  15.41745925 11.18093495
   7.35925264  1.64502986  0.25817893  1.95529163]
 [ 0.97949016  9.4748477   4.3178397   1.28785563 11.18670039  8.28358441
  12.84770186  2.27205699  5.83754103  8.29326745]
 [ 6.81349283  7.26929517 13.53117833  2.75655603  3.97987996  1.80361244
   3.40930917 14.59595733 10.33825664  6.89666956]
 [ 2.6424478   4.14372498  4.6120737   6.78997063  3.60305843  8.08492421
   1.0186117  12.54807116  5.76294786  1.02639398]
 [ 4.51969603  0.12887668  1.92674964  8.23029078  2.17874852  5.89014832
   5.23162031  8.29498612  1.56311322  2.99056775]


### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a fill value when necessary) (★★★)

In [245]:
Z = np.random.randint(0,10,(10,10))

shape = (5,5)

fill = 0

position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill

P = np.array(list(position)).astype(int)

Rs = np.array(list(R.shape)).astype(int)

Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)

R_stop = np.array(list(shape)).astype(int)

Z_start = (P-Rs//2)

Z_stop = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()

Z_start = (np.maximum(Z_start,0)).tolist()

R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()

Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]

z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]

R[r] = Z[z]

print(Z)

print(R)

[[8 3 5 6 6 4 3 1 7 0]
 [1 0 1 6 1 9 4 9 6 3]
 [4 5 6 2 4 8 6 4 1 2]
 [3 7 8 1 6 6 0 6 9 0]
 [2 8 1 4 9 2 5 5 6 0]
 [9 9 1 9 9 6 3 5 9 5]
 [4 6 5 5 4 7 8 1 5 8]
 [0 1 4 2 9 9 2 4 6 9]
 [8 1 6 0 9 6 6 6 3 1]
 [2 1 4 5 1 6 3 7 5 3]]
[[0 0 0 0 0]
 [0 8 3 5 6]
 [0 1 0 1 6]
 [0 4 5 6 2]
 [0 3 7 8 1]]


### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [246]:
Z = np.arange(1,15,dtype=np.uint32)

R = stride_tricks.as_strided(Z,(11,4),(4,4))

print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


### 82. Compute a matrix rank (★★★)

In [248]:
Z = np.random.uniform(0,1,(20,20))

U, S, V = np.linalg.svd(Z)

rank = np.sum(S > 1e-10)

print(rank)

20


### 83. How to find the most frequent value in an array?

In [253]:
Z = np.random.randint(0,10,60)

print(np.bincount(Z).argmax())

7


### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [254]:
Z = np.random.randint(0,5,(10,10))

n = 3

i = 1 + (Z.shape[0]-3)

j = 1 + (Z.shape[1]-3)

C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)

print(C)

[[[[3 2 3]
   [0 2 3]
   [2 0 0]]

  [[2 3 2]
   [2 3 4]
   [0 0 3]]

  [[3 2 2]
   [3 4 0]
   [0 3 0]]

  [[2 2 4]
   [4 0 2]
   [3 0 2]]

  [[2 4 2]
   [0 2 0]
   [0 2 4]]

  [[4 2 2]
   [2 0 0]
   [2 4 1]]

  [[2 2 0]
   [0 0 4]
   [4 1 1]]

  [[2 0 3]
   [0 4 3]
   [1 1 0]]]


 [[[0 2 3]
   [2 0 0]
   [1 4 3]]

  [[2 3 4]
   [0 0 3]
   [4 3 0]]

  [[3 4 0]
   [0 3 0]
   [3 0 0]]

  [[4 0 2]
   [3 0 2]
   [0 0 4]]

  [[0 2 0]
   [0 2 4]
   [0 4 0]]

  [[2 0 0]
   [2 4 1]
   [4 0 3]]

  [[0 0 4]
   [4 1 1]
   [0 3 2]]

  [[0 4 3]
   [1 1 0]
   [3 2 4]]]


 [[[2 0 0]
   [1 4 3]
   [0 2 2]]

  [[0 0 3]
   [4 3 0]
   [2 2 2]]

  [[0 3 0]
   [3 0 0]
   [2 2 3]]

  [[3 0 2]
   [0 0 4]
   [2 3 0]]

  [[0 2 4]
   [0 4 0]
   [3 0 2]]

  [[2 4 1]
   [4 0 3]
   [0 2 2]]

  [[4 1 1]
   [0 3 2]
   [2 2 4]]

  [[1 1 0]
   [3 2 4]
   [2 4 3]]]


 [[[1 4 3]
   [0 2 2]
   [4 0 2]]

  [[4 3 0]
   [2 2 2]
   [0 2 4]]

  [[3 0 0]
   [2 2 3]
   [2 4 0]]

  [[0 0 4]
   [2 3 0]
   [4 0 2]]

  [[0 4 0]
   

### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [260]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
     return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))

S[2,3] = 50

print(S)

[[ 3 11  4  3  8]
 [11  4  9  1  4]
 [ 4  9  4 50 16]
 [ 3  1 50  2  5]
 [ 8  4 16  5  1]]


### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [262]:
p, n = 20, 30

M = np.ones((p,n,n))

V = np.ones((p,n,1))

S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])

print(S)

[[600.]
 [600.]
 [600.]
 [600.]
 [600.]
 [600.]
 [600.]
 [600.]
 [600.]
 [600.]
 [600.]
 [600.]
 [600.]
 [600.]
 [600.]
 [600.]
 [600.]
 [600.]
 [600.]
 [600.]
 [600.]
 [600.]
 [600.]
 [600.]
 [600.]
 [600.]
 [600.]
 [600.]
 [600.]
 [600.]]


### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [263]:
Z = np.ones((16,16))

k = 4

S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),

np.arange(0, Z.shape[1], k), axis=1)

print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [264]:
def iterate(Z):
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +Z[1:-1,0:-2] + Z[1:-1,2:] +Z[2: ,0:-2] + Z[2: ,1:-1] + Z[2: ,2:])
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))

for i in range(100): Z = iterate(Z)

print(Z)

[[0 0 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


### 89. How to get the n largest values of an array (★★★)

In [266]:
Z = np.arange(100000)

np.random.shuffle(Z)

n = 5

print (Z[np.argsort(Z)[-n:]])

[99995 99996 99997 99998 99999]


### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [267]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)
    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T
    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]
        return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 0 0]
 [1 0 1]
 [1 1 0]
 [1 1 1]
 [2 0 0]
 [2 0 1]
 [2 1 0]
 [2 1 1]
 [3 0 0]
 [3 0 1]
 [3 1 0]
 [3 1 1]]


### 91. How to create a record array from a regular array? (★★★)

In [269]:
Z = np.array([("Hello", 2.5, 3),("World", 3.6, 2)])

R = np.core.records.fromarrays(Z.T,names='col1, col2, col3',formats = 'S8, f8, i8')

print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods(★★★)

### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B?(★★★)

In [273]:
A = np.random.randint(0,5,(8,3))

B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)

rows = (C.sum(axis=(1,2,3)) >= B.shape[1]).nonzero()[0]

print(rows)

[0 1 3 4 5 6 7]


### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [274]:
Z = np.random.randint(0,5,(10,3))

E = np.logical_and.reduce(Z[:,1:] == Z[:,:-1], axis=1)

U = Z[~E]

print(Z)

print(U)

[[1 2 3]
 [1 3 4]
 [2 0 3]
 [4 4 4]
 [0 0 1]
 [0 4 4]
 [1 4 3]
 [1 4 0]
 [1 3 4]
 [3 0 1]]
[[1 2 3]
 [1 3 4]
 [2 0 3]
 [0 0 1]
 [0 4 4]
 [1 4 3]
 [1 4 0]
 [1 3 4]
 [3 0 1]]


### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [275]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])

B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)

print(B[:,::-1])

# Author: Daniel T. McDonald

I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)

print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [276]:
Z = np.random.randint(0,2,(6,3))

T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))

_, idx = np.unique(T, return_index=True)

uZ = Z[idx]

print(uZ)

[[0 0 0]
 [0 0 1]
 [0 1 1]
 [1 1 0]]


### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [277]:
A = np.random.uniform(0,1,10)

B = np.random.uniform(0,1,10)

np.einsum('i->', A) # np.sum(A)

np.einsum('i,i->i', A, B) # A * B

np.einsum('i,i', A, B) # np.inner(A, B)

np.einsum('i,j', A, B) # np.outer(A, B)

array([[0.27323721, 0.10068276, 0.06855984, 0.30732642, 0.13096782,
        0.32528275, 0.1300971 , 0.29112315, 0.43743973, 0.15465996],
       [0.09878478, 0.03640033, 0.02478677, 0.11110921, 0.04734943,
        0.11760105, 0.04703464, 0.10525117, 0.15814971, 0.05591497],
       [0.0501316 , 0.01847255, 0.01257887, 0.05638605, 0.02402904,
        0.05968055, 0.02386928, 0.05341319, 0.0802583 , 0.0283759 ],
       [0.18086731, 0.06664619, 0.04538267, 0.2034324 , 0.08669316,
        0.21531846, 0.08611679, 0.19270677, 0.28955993, 0.102376  ],
       [0.4896265 , 0.18041813, 0.12285556, 0.55071253, 0.23468734,
        0.58288932, 0.23312706, 0.52167714, 0.78386863, 0.2771424 ],
       [0.20824905, 0.07673585, 0.05225321, 0.2342303 , 0.09981775,
        0.2479158 , 0.09915413, 0.2218809 , 0.33339678, 0.11787483],
       [0.05902761, 0.02175056, 0.01481103, 0.06639192, 0.02829306,
        0.07027104, 0.02810496, 0.06289152, 0.09450038, 0.03341129],
       [0.21524217, 0.07931268, 0.0540079

### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [280]:
phi = np.arange(0, 10*np.pi, 0.1)

a = 1

x = a*phi*np.cos(phi)

y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths

r = np.zeros_like(x)

r[1:] = np.cumsum(dr) # integrate path

r_int = np.linspace(0, r.max(), 200) # regular spaced path

x_int = np.interp(r_int, r, x) # integrate path

y_int = np.interp(r_int, r, y)
print(y_int,x_int,r_int,sep='\n')

[ 0.00000000e+00  1.74026724e+00  9.81816584e-01 -1.34251287e+00
 -3.53191891e+00 -4.70449474e+00 -4.59573427e+00 -3.33831870e+00
 -1.28956083e+00  1.14234685e+00  3.55645601e+00  5.62188218e+00
  7.09389488e+00  7.82951803e+00  7.78700678e+00  6.99685666e+00
  5.55535240e+00  3.60417006e+00  1.30506373e+00 -1.15819722e+00
 -3.61328132e+00 -5.89130465e+00 -7.87065053e+00 -9.41689057e+00
 -1.04714836e+01 -1.09903787e+01 -1.09354306e+01 -1.03330912e+01
 -9.22690166e+00 -7.67489830e+00 -5.75257980e+00 -3.54832201e+00
 -1.15854355e+00  1.31709956e+00  3.78023622e+00  6.13780326e+00
  8.30540149e+00  1.02098724e+01  1.17910419e+01  1.29972950e+01
  1.37774249e+01  1.41319792e+01  1.40585758e+01  1.35636816e+01
  1.26345244e+01  1.13409083e+01  9.72216360e+00  7.79464305e+00
  5.64544223e+00  3.32503222e+00  8.88107041e-01 -1.59329248e+00
 -4.05992507e+00 -6.45313746e+00 -8.71327144e+00 -1.07900854e+01
 -1.26380653e+01 -1.42147006e+01 -1.54892299e+01 -1.64390858e+01
 -1.70351433e+01 -1.72938

### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [281]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],

[2.0, 0.0, 1.0, 1.0],

[1.5, 2.5, 1.0, 0.0]])

n = 4

M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)

M &= (X.sum(axis=-1) == n)

print(X[M])

[[2. 0. 1. 1.]]


### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the meanof each sample, and then compute percentiles over the means). (★★★)

In [282]:
X = np.random.randn(100) # random 1D array

N = 1000 # number of bootstrap samples

idx = np.random.randint(0, X.size, (N, X.size))

means = X[idx].mean(axis=1)

confint = np.percentile(means, [2.5, 97.5])

print(confint)

[-0.07982128  0.29966278]
